<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
if($customerSession->isLoggedIn()):
    ?>
    <?php $data = $customerSession->getData();
         if(isset($data['avatar'])):
        ?>
        <div class="box-content">
            <img style="height:175px;" src='<?php echo $block->getImage(); ?>'>
        </div>
         <?php endif; ?>
<?php endif; ?>