
<h2>Modal Test Page</h2>
<div data-mage-init='{"mymodal": {}}'>
    <button id="open-modal">Open Login Modal</button>
</div>
<div id="popup-mpdal" style="display:none;" >
    <form method="post" action="index.html">
        <div class="box">
            <h1>Hello World</h1>

            <input type="email" name="email" value="email"  class="email" />

            <input type="password" name="email" value="email"  class="email" />

            <a href="#"><div class="btn">Log in</div></a> <!-- End Btn -->

        </div> <!-- End Box -->

    </form>
</div>
<script>
    require([
        "mymodal"
    ]);
</script>
<style>
    p{
        font-size:12px;
        text-decoration: none;
        color:#ffffff;
    }

    h1{
        font-size:1.5em;
        color:#525252;
    }

    .box{
        background:white;
        width:300px;
        border-radius:6px;
        margin: 0 auto 0 auto;
        padding:0px 0px 70px 0px;
    }

    .email{
        background:#ecf0f1;
        border: #ccc 1px solid;
        border-bottom: #ccc 2px solid;
        padding: 8px;
        width:250px;
        color:#AAAAAA;
        margin-top:10px;
        font-size:1em;
        border-radius:4px;
    }

    .password{
        border-radius:4px;
        background:#ecf0f1;
        border: #ccc 1px solid;
        padding: 8px;
        width:250px;
        font-size:1em;
    }

    .btn{
        background:#eb5202;
        width:125px;
        padding-top:5px;
        padding-bottom:5px;
        color:white;
        border-radius:4px;
        border: #eb5202 1px solid;
        margin-top:20px;
        margin-bottom:20px;
        margin-left:16px;
        font-weight:800;
        font-size:0.8em;
    }

    .btn:hover{
        background: #bb4202;
    }

</style>
