<h2>Watch movie!</h2>

<table>
    <tr>
        <td><b>Movie Name</b></td>
        <td><b>Director</b></td>
        <td><b>Actors</b></td>
    </tr>
    <?php foreach ($block->getMovie() as $movie): ?>
    <tr>
        <td><?php echo $movie['name'] ?></td>
        <td><?php echo $movie['dname'] ?></td>
        <td>
            <ul>
                <?php foreach ($block->getActor($movie['movie_id']) as $actor): ?>
                    <li> <?php echo $actor['aname'] ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </td>
    </tr>
    <?php endforeach; ?>
</table>